import type { LaunchBackend } from "../hardware.js";

export type ModelQuantization = "fp16" | "awq" | "gptq";
export type ModelSizeClass = "small" | "medium" | "large";

export interface CatalogModel {
  id: string;
  name: string;
  hfRepo: string;
  family: string;
  /** Product line for newest-generation recommendations (qwen, gemma, llama, …). */
  lineage: string;
  /** Higher is newer within `lineage` (3.8 > 3.5 > 3 > 2.5). */
  generation: number;
  paramsB: number;
  quantization: ModelQuantization;
  /** Approximate on-disk / loaded weights, not including KV cache. */
  weightsMiB: number;
  sizeClass: ModelSizeClass;
  /** Tiny enough to attempt without a GPU (still often slow / unsupported by vLLM). */
  cpuFeasible: boolean;
  gated: boolean;
  /** Passed to `vllm serve --quantization` when set. CUDA/ROCm only. */
  vllmQuantization?: "awq" | "gptq";
  /** Launch backends that can load this snapshot. Default: fp16 → all GPUs; AWQ/GPTQ → CUDA/ROCm. */
  compatibleBackends?: Exclude<LaunchBackend, "cpu">[];
  notes?: string;
}

/** AWQ/GPTQ snapshots in this catalog use CUDA/ROCm kernels; Intel XPU vLLM serves FP16. */
const CUDA_ROCM: Exclude<LaunchBackend, "cpu">[] = ["cuda", "rocm"];

const AWQ_NOTE = "AWQ: CUDA/ROCm vLLM. Use the fp16 snapshot on Intel XPU.";
const GPTQ_NOTE = "GPTQ: CUDA/ROCm vLLM. Use the fp16 snapshot on Intel XPU.";
const GEMMA4_NOTE =
  "Ungated Apache-2.0 (Gemma 4). Natively multimodal on Hugging Face; this app’s vLLM path is text chat (`vllm serve`, `--trust-remote-code`). Vision/audio inputs are not used here.";
const GEMMA3_VLM_NOTE =
  "Gemma 3 Instruct (Gemma Terms of Use, gated). 4B+ checkpoints are image-text-to-text VLMs; this app’s vLLM path is text chat. Prefer Gemma 4 when it fits.";
const QWEN35_NOTE =
  "Ungated Apache-2.0. Post-trained chat (thinking by default). Native VLM on Hub; this app serves text via vLLM. Needs a recent vLLM with Qwen3.5 kernels.";
const QWEN38_NOTE =
  "Ungated Apache-2.0. Newest Qwen dense open weights as of 2026-08 (thinking by default). Native VLM; this app serves text via vLLM. Needs a recent vLLM with Qwen3.5/3.8 kernels.";
const GEMMA_GATE_NOTE =
  "Gemma weights are free to use under Google’s Gemma Terms of Use; the Hugging Face repo is gated. Accept the terms on the model card while logged into Hugging Face, then paste a read token in Settings → Local models (HF_TOKEN).";
const LLAMA_GATE_NOTE =
  "Gated Hugging Face repo under Meta’s Llama Community License. Accept the license on the model card while logged into Hugging Face, then paste a read token in Settings → Local models (HF_TOKEN).";
const LLAMA4_GATE_NOTE =
  "Gated Hugging Face repo under the Llama 4 Community License. Accept the license on the model card while logged into Hugging Face, then paste a read token in Settings → Local models (HF_TOKEN). Natively multimodal; this app’s vLLM path is text chat.";
const LLAMA_AWQ_NOTE =
  "Ungated Hugging Face snapshot of Llama 3.1; Meta’s Llama Community License still applies. AWQ: CUDA/ROCm vLLM. Use the fp16 snapshot on Intel XPU.";
const MISTRAL_GATE_NOTE =
  "Gated Hugging Face repo (Apache-2.0). Accept access on the model card while logged into Hugging Face, then paste a read token in Settings → Local models (HF_TOKEN).";

export function catalogCompatibleWith(model: CatalogModel, backend: LaunchBackend): boolean {
  if (backend === "cpu") return model.cpuFeasible;
  if (model.compatibleBackends) return model.compatibleBackends.includes(backend);
  if (model.quantization === "awq" || model.quantization === "gptq") return CUDA_ROCM.includes(backend);
  return true;
}

/**
 * Curated open-weight chat models commonly served by vLLM (any CUDA, ROCm, or Intel XPU host).
 * VRAM figures are approximate serving weights (fp16 ≈ 2 bytes/param; 4-bit ≈ 0.6–0.7 bytes/param).
 * Fit is computed from detected accelerators, not a vendor preset.
 *
 * Recommendations: every catalog row (no top-N cap). Fit is labeled; older generations stay
 * listed. `sizeSlot` / `isNewestHubId` mark the newest Hub id in each size class (Gemma 4 over
 * Gemma 3/2, Qwen3.8 over Qwen2.5) without hiding the rest.
 *
 * Not catalogued (cannot serve as text chat here, or not a practical local snapshot):
 * - Gemma 3n, Gemma 4 base (non-IT), DiffusionGemma (block-diffusion, not autoregressive chat).
 * - Qwen3.8-2.4T-A95B / Qwen3.8-Flash-Next: far beyond typical local VRAM.
 * - Llama 4 Maverick (400B total). Ministral 3 official Hub snapshots are FP8-native (not fp16/AWQ).
 * - DeepSeek-V3/V4 full checkpoints. Embedding / vision-only / image-generation weights.
 * Gemma 3 IT is catalogued as an older generation (1B text-only; 4B+ are VLMs served as text here).
 */
export const LOCAL_MODEL_CATALOG: CatalogModel[] = [
  {
    id: "qwen2.5-0.5b-instruct",
    name: "Qwen2.5 0.5B Instruct",
    hfRepo: "Qwen/Qwen2.5-0.5B-Instruct",
    family: "qwen2.5-0.5b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 0.5,
    quantization: "fp16",
    weightsMiB: 1_000,
    sizeClass: "small",
    cpuFeasible: true,
    gated: false,
    notes: "Tiny; CPU-feasible. Quality is limited; use only when no GPU is present.",
  },
  {
    id: "qwen2.5-1.5b-instruct",
    name: "Qwen2.5 1.5B Instruct",
    hfRepo: "Qwen/Qwen2.5-1.5B-Instruct",
    family: "qwen2.5-1.5b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 1.5,
    quantization: "fp16",
    weightsMiB: 3_100,
    sizeClass: "small",
    cpuFeasible: true,
    gated: false,
    notes: "Small; marked CPU-feasible. Prefer a 7B GPU model when VRAM allows.",
  },
  {
    id: "qwen2.5-7b-instruct",
    name: "Qwen2.5 7B Instruct",
    hfRepo: "Qwen/Qwen2.5-7B-Instruct",
    family: "qwen2.5-7b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 7,
    quantization: "fp16",
    weightsMiB: 14_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen2.5-7b-instruct-awq",
    name: "Qwen2.5 7B Instruct AWQ",
    hfRepo: "Qwen/Qwen2.5-7B-Instruct-AWQ",
    family: "qwen2.5-7b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 7,
    quantization: "awq",
    weightsMiB: 5_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    compatibleBackends: CUDA_ROCM,
    notes: AWQ_NOTE,
  },
  {
    id: "gemma-2-2b-it",
    name: "Gemma 2 2B Instruct",
    hfRepo: "google/gemma-2-2b-it",
    family: "gemma-2-2b",
    lineage: "gemma",
    generation: 2,
    paramsB: 2.6,
    quantization: "fp16",
    weightsMiB: 5_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: GEMMA_GATE_NOTE,
  },
  {
    id: "gemma-2-9b-it",
    name: "Gemma 2 9B Instruct",
    hfRepo: "google/gemma-2-9b-it",
    family: "gemma-2-9b",
    lineage: "gemma",
    generation: 2,
    paramsB: 9.2,
    quantization: "fp16",
    weightsMiB: 18_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: GEMMA_GATE_NOTE,
  },
  {
    id: "gemma-2-27b-it",
    name: "Gemma 2 27B Instruct",
    hfRepo: "google/gemma-2-27b-it",
    family: "gemma-2-27b",
    lineage: "gemma",
    generation: 2,
    paramsB: 27.2,
    quantization: "fp16",
    weightsMiB: 52_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: true,
    notes: `${GEMMA_GATE_NOTE} Needs ~62 GiB with KV headroom (80GB-class or two ~32 GiB GPUs).`,
  },
  {
    id: "gemma-3-1b-it",
    name: "Gemma 3 1B Instruct",
    hfRepo: "google/gemma-3-1b-it",
    family: "gemma-3-1b",
    lineage: "gemma",
    generation: 3,
    paramsB: 1,
    quantization: "fp16",
    weightsMiB: 3_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: `${GEMMA_GATE_NOTE} Text-only 1B Instruct (not multimodal). Older generation; prefer Gemma 4 when it fits.`,
  },
  {
    id: "gemma-3-4b-it",
    name: "Gemma 3 4B Instruct",
    hfRepo: "google/gemma-3-4b-it",
    family: "gemma-3-4b",
    lineage: "gemma",
    generation: 3,
    paramsB: 4.3,
    quantization: "fp16",
    weightsMiB: 8_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: GEMMA3_VLM_NOTE,
  },
  {
    id: "gemma-3-12b-it",
    name: "Gemma 3 12B Instruct",
    hfRepo: "google/gemma-3-12b-it",
    family: "gemma-3-12b",
    lineage: "gemma",
    generation: 3,
    paramsB: 12.2,
    quantization: "fp16",
    weightsMiB: 24_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: true,
    notes: GEMMA3_VLM_NOTE,
  },
  {
    id: "gemma-3-27b-it",
    name: "Gemma 3 27B Instruct",
    hfRepo: "google/gemma-3-27b-it",
    family: "gemma-3-27b",
    lineage: "gemma",
    generation: 3,
    paramsB: 27.4,
    quantization: "fp16",
    weightsMiB: 54_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: true,
    notes: `${GEMMA3_VLM_NOTE} Needs ~65 GiB with KV headroom (80GB-class or two ~32 GiB GPUs).`,
  },
  {
    id: "gemma-4-e2b-it",
    name: "Gemma 4 E2B Instruct",
    hfRepo: "google/gemma-4-E2B-it",
    family: "gemma-4-e2b",
    lineage: "gemma",
    generation: 4,
    paramsB: 5.1,
    quantization: "fp16",
    weightsMiB: 10_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: `${GEMMA4_NOTE} Effective ~2.3B (5.1B with per-layer embeddings).`,
  },
  {
    id: "gemma-4-e4b-it",
    name: "Gemma 4 E4B Instruct",
    hfRepo: "google/gemma-4-E4B-it",
    family: "gemma-4-e4b",
    lineage: "gemma",
    generation: 4,
    paramsB: 8,
    quantization: "fp16",
    weightsMiB: 15_500,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: `${GEMMA4_NOTE} Effective ~4.5B (8B with embeddings).`,
  },
  {
    id: "gemma-4-12b-it",
    name: "Gemma 4 12B Instruct",
    hfRepo: "google/gemma-4-12B-it",
    family: "gemma-4-12b",
    lineage: "gemma",
    generation: 4,
    paramsB: 12,
    quantization: "fp16",
    weightsMiB: 23_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: `${GEMMA4_NOTE} Encoder-free unified 12B; typically needs ~24GB+ or two GPUs.`,
  },
  {
    id: "gemma-4-26b-a4b-it",
    name: "Gemma 4 26B-A4B Instruct",
    hfRepo: "google/gemma-4-26B-A4B-it",
    family: "gemma-4-26b-a4b",
    lineage: "gemma",
    generation: 4,
    paramsB: 25.8,
    quantization: "fp16",
    weightsMiB: 49_500,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: `${GEMMA4_NOTE} MoE 25.8B total / ~4B active. Needs ~60 GiB with KV headroom (80GB-class or two ~32 GiB GPUs).`,
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B Instruct",
    hfRepo: "google/gemma-4-31B-it",
    family: "gemma-4-31b",
    lineage: "gemma",
    generation: 4,
    paramsB: 31.3,
    quantization: "fp16",
    weightsMiB: 60_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: `${GEMMA4_NOTE} Dense 31B. Needs ~72 GiB with KV headroom (80GB-class or two ~40 GiB GPUs).`,
  },
  {
    id: "qwen3-4b",
    name: "Qwen3 4B",
    hfRepo: "Qwen/Qwen3-4B",
    family: "qwen3-4b",
    lineage: "qwen",
    generation: 3,
    paramsB: 4,
    quantization: "fp16",
    weightsMiB: 8_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen3-4b-awq",
    name: "Qwen3 4B AWQ",
    hfRepo: "Qwen/Qwen3-4B-AWQ",
    family: "qwen3-4b",
    lineage: "qwen",
    generation: 3,
    paramsB: 4,
    quantization: "awq",
    weightsMiB: 3_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    compatibleBackends: CUDA_ROCM,
    notes: AWQ_NOTE,
  },
  {
    id: "qwen3-8b",
    name: "Qwen3 8B",
    hfRepo: "Qwen/Qwen3-8B",
    family: "qwen3-8b",
    lineage: "qwen",
    generation: 3,
    paramsB: 8.2,
    quantization: "fp16",
    weightsMiB: 16_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen3-8b-awq",
    name: "Qwen3 8B AWQ",
    hfRepo: "Qwen/Qwen3-8B-AWQ",
    family: "qwen3-8b",
    lineage: "qwen",
    generation: 3,
    paramsB: 8.2,
    quantization: "awq",
    weightsMiB: 6_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    compatibleBackends: CUDA_ROCM,
    notes: AWQ_NOTE,
  },
  {
    id: "qwen3-14b",
    name: "Qwen3 14B",
    hfRepo: "Qwen/Qwen3-14B",
    family: "qwen3-14b",
    lineage: "qwen",
    generation: 3,
    paramsB: 14.8,
    quantization: "fp16",
    weightsMiB: 28_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen3-14b-awq",
    name: "Qwen3 14B AWQ",
    hfRepo: "Qwen/Qwen3-14B-AWQ",
    family: "qwen3-14b",
    lineage: "qwen",
    generation: 3,
    paramsB: 14.8,
    quantization: "awq",
    weightsMiB: 10_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    compatibleBackends: CUDA_ROCM,
    notes: AWQ_NOTE,
  },
  {
    id: "qwen3-0.6b",
    name: "Qwen3 0.6B",
    hfRepo: "Qwen/Qwen3-0.6B",
    family: "qwen3-0.6b",
    lineage: "qwen",
    generation: 3,
    paramsB: 0.6,
    quantization: "fp16",
    weightsMiB: 1_200,
    sizeClass: "small",
    cpuFeasible: true,
    gated: false,
    notes: "Tiny; CPU-feasible. Quality is limited; use only when no GPU is present.",
  },
  {
    id: "qwen3-1.7b",
    name: "Qwen3 1.7B",
    hfRepo: "Qwen/Qwen3-1.7B",
    family: "qwen3-1.7b",
    lineage: "qwen",
    generation: 3,
    paramsB: 1.7,
    quantization: "fp16",
    weightsMiB: 3_400,
    sizeClass: "small",
    cpuFeasible: true,
    gated: false,
    notes: "Small; marked CPU-feasible. Prefer a GPU model when VRAM allows.",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    hfRepo: "Qwen/Qwen3-32B",
    family: "qwen3-32b",
    lineage: "qwen",
    generation: 3,
    paramsB: 32.8,
    quantization: "fp16",
    weightsMiB: 64_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen3-32b-awq",
    name: "Qwen3 32B AWQ",
    hfRepo: "Qwen/Qwen3-32B-AWQ",
    family: "qwen3-32b",
    lineage: "qwen",
    generation: 3,
    paramsB: 32.8,
    quantization: "awq",
    weightsMiB: 20_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    compatibleBackends: CUDA_ROCM,
    notes: AWQ_NOTE,
  },
  {
    id: "qwen3.5-0.8b",
    name: "Qwen3.5 0.8B",
    hfRepo: "Qwen/Qwen3.5-0.8B",
    family: "qwen3.5-0.8b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 0.87,
    quantization: "fp16",
    weightsMiB: 1_700,
    sizeClass: "small",
    cpuFeasible: true,
    gated: false,
    notes: `${QWEN35_NOTE} Tiny; CPU-feasible. Quality is limited; use only when no GPU is present.`,
  },
  {
    id: "qwen3.5-2b",
    name: "Qwen3.5 2B",
    hfRepo: "Qwen/Qwen3.5-2B",
    family: "qwen3.5-2b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 2.3,
    quantization: "fp16",
    weightsMiB: 4_400,
    sizeClass: "small",
    cpuFeasible: true,
    gated: false,
    notes: `${QWEN35_NOTE} Small; marked CPU-feasible. Prefer a GPU model when VRAM allows.`,
  },
  {
    id: "qwen3.5-4b",
    name: "Qwen3.5 4B",
    hfRepo: "Qwen/Qwen3.5-4B",
    family: "qwen3.5-4b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 4.7,
    quantization: "fp16",
    weightsMiB: 9_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: QWEN35_NOTE,
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    hfRepo: "Qwen/Qwen3.5-9B",
    family: "qwen3.5-9b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 9.7,
    quantization: "fp16",
    weightsMiB: 18_500,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: QWEN35_NOTE,
  },
  {
    id: "qwen3.5-27b",
    name: "Qwen3.5 27B",
    hfRepo: "Qwen/Qwen3.5-27B",
    family: "qwen3.5-27b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 27.8,
    quantization: "fp16",
    weightsMiB: 53_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: `${QWEN35_NOTE} Needs ~64 GiB with KV headroom (80GB-class or two ~32 GiB GPUs).`,
  },
  {
    id: "qwen3.5-27b-gptq",
    name: "Qwen3.5 27B GPTQ Int4",
    hfRepo: "Qwen/Qwen3.5-27B-GPTQ-Int4",
    family: "qwen3.5-27b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 27.8,
    quantization: "gptq",
    weightsMiB: 17_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "gptq",
    compatibleBackends: CUDA_ROCM,
    notes: `${GPTQ_NOTE} Official 4-bit of Qwen3.5 27B.`,
  },
  {
    id: "qwen3.5-35b-a3b",
    name: "Qwen3.5 35B-A3B",
    hfRepo: "Qwen/Qwen3.5-35B-A3B",
    family: "qwen3.5-35b-a3b",
    lineage: "qwen",
    generation: 3.5,
    paramsB: 36,
    quantization: "fp16",
    weightsMiB: 69_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: `${QWEN35_NOTE} MoE ~36B total / ~3B active. Needs ~80GB-class or multi-GPU.`,
  },
  {
    id: "qwen3.8-27b",
    name: "Qwen3.8 27B",
    hfRepo: "Qwen/Qwen3.8-27B",
    family: "qwen3.8-27b",
    lineage: "qwen",
    generation: 3.8,
    paramsB: 27.8,
    quantization: "fp16",
    weightsMiB: 53_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: `${QWEN38_NOTE} Needs ~64 GiB with KV headroom (80GB-class or two ~32 GiB GPUs).`,
  },
  {
    id: "phi-4-mini-instruct",
    name: "Phi-4 Mini Instruct",
    hfRepo: "microsoft/Phi-4-mini-instruct",
    family: "phi-4-mini",
    lineage: "phi",
    generation: 4,
    paramsB: 3.8,
    quantization: "fp16",
    weightsMiB: 7_500,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated MIT. Custom modeling code; vLLM is started with --trust-remote-code.",
  },
  {
    id: "phi-4",
    name: "Phi-4",
    hfRepo: "microsoft/phi-4",
    family: "phi-4",
    lineage: "phi",
    generation: 4,
    paramsB: 14.7,
    quantization: "fp16",
    weightsMiB: 28_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated MIT. ~14.7B; typically needs ~24GB+ or two GPUs in fp16.",
  },
  {
    id: "olmo-2-13b-instruct",
    name: "OLMo 2 13B Instruct",
    hfRepo: "allenai/OLMo-2-1124-13B-Instruct",
    family: "olmo-2-13b",
    lineage: "olmo",
    generation: 2,
    paramsB: 13.7,
    quantization: "fp16",
    weightsMiB: 26_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (Ai2).",
  },
  {
    id: "olmo-3-7b-instruct",
    name: "OLMo 3 7B Instruct",
    hfRepo: "allenai/Olmo-3-7B-Instruct",
    family: "olmo-3-7b",
    lineage: "olmo",
    generation: 3,
    paramsB: 7.3,
    quantization: "fp16",
    weightsMiB: 14_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (Ai2). Text-only instruct; vLLM Olmo3ForCausalLM.",
  },
  {
    id: "olmo-3.1-32b-instruct",
    name: "OLMo 3.1 32B Instruct",
    hfRepo: "allenai/Olmo-3.1-32B-Instruct",
    family: "olmo-3.1-32b",
    lineage: "olmo",
    generation: 3.1,
    paramsB: 32.2,
    quantization: "fp16",
    weightsMiB: 61_500,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (Ai2). Newest OLMo instruct 32B. Needs ~74 GiB with KV headroom (80GB-class or two ~40 GiB GPUs).",
  },
  {
    id: "granite-3.3-8b-instruct",
    name: "Granite 3.3 8B Instruct",
    hfRepo: "ibm-granite/granite-3.3-8b-instruct",
    family: "granite-3.3-8b",
    lineage: "granite",
    generation: 3.3,
    paramsB: 8.2,
    quantization: "fp16",
    weightsMiB: 16_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (IBM).",
  },
  {
    id: "granite-4.2-3b",
    name: "Granite 4.2 3B",
    hfRepo: "ibm-granite/granite-4.2-3b",
    family: "granite-4.2-3b",
    lineage: "granite",
    generation: 4.2,
    paramsB: 3.7,
    quantization: "fp16",
    weightsMiB: 7_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (IBM). Text instruct with thinking; vLLM 0.20+ recommended.",
  },
  {
    id: "granite-4.2-8b",
    name: "Granite 4.2 8B",
    hfRepo: "ibm-granite/granite-4.2-8b",
    family: "granite-4.2-8b",
    lineage: "granite",
    generation: 4.2,
    paramsB: 8.8,
    quantization: "fp16",
    weightsMiB: 17_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (IBM). Text instruct with thinking; vLLM 0.20+ recommended.",
  },
  {
    id: "granite-4.2-30b",
    name: "Granite 4.2 30B",
    hfRepo: "ibm-granite/granite-4.2-30b",
    family: "granite-4.2-30b",
    lineage: "granite",
    generation: 4.2,
    paramsB: 29.3,
    quantization: "fp16",
    weightsMiB: 56_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0 (IBM). Needs ~67 GiB with KV headroom (80GB-class or two ~32 GiB GPUs).",
  },
  {
    id: "deepseek-r1-distill-qwen-7b",
    name: "DeepSeek-R1 Distill Qwen 7B",
    hfRepo: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    family: "deepseek-r1-qwen-7b",
    lineage: "deepseek",
    generation: 1,
    paramsB: 7.6,
    quantization: "fp16",
    weightsMiB: 15_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated MIT. Reasoning distill; longer traces than a plain 7B chat model.",
  },
  {
    id: "deepseek-r1-distill-qwen-14b",
    name: "DeepSeek-R1 Distill Qwen 14B",
    hfRepo: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    family: "deepseek-r1-qwen-14b",
    lineage: "deepseek",
    generation: 1,
    paramsB: 14.8,
    quantization: "fp16",
    weightsMiB: 28_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated MIT. Reasoning distill; typically needs ~24GB+ or two GPUs in fp16.",
  },
  {
    id: "deepseek-r1-0528-qwen3-8b",
    name: "DeepSeek-R1-0528 Qwen3 8B",
    hfRepo: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
    family: "deepseek-r1-0528-qwen3-8b",
    lineage: "deepseek",
    generation: 1.0528,
    paramsB: 8.2,
    quantization: "fp16",
    weightsMiB: 16_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated MIT. Newer R1-0528 distill on Qwen3 8B; longer traces than a plain 8B chat model.",
  },
  {
    id: "llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    hfRepo: "meta-llama/Llama-3.1-8B-Instruct",
    family: "llama-3.1-8b",
    lineage: "llama",
    generation: 3.1,
    paramsB: 8,
    quantization: "fp16",
    weightsMiB: 16_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: LLAMA_GATE_NOTE,
  },
  {
    id: "llama-3.1-8b-instruct-awq",
    name: "Llama 3.1 8B Instruct AWQ",
    hfRepo: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4",
    family: "llama-3.1-8b",
    lineage: "llama",
    generation: 3.1,
    paramsB: 8,
    quantization: "awq",
    weightsMiB: 5_500,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    compatibleBackends: CUDA_ROCM,
    notes: LLAMA_AWQ_NOTE,
  },
  {
    id: "llama-3.2-1b-instruct",
    name: "Llama 3.2 1B Instruct",
    hfRepo: "meta-llama/Llama-3.2-1B-Instruct",
    family: "llama-3.2-1b",
    lineage: "llama",
    generation: 3.2,
    paramsB: 1.2,
    quantization: "fp16",
    weightsMiB: 3_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: LLAMA_GATE_NOTE,
  },
  {
    id: "llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    hfRepo: "meta-llama/Llama-3.2-3B-Instruct",
    family: "llama-3.2-3b",
    lineage: "llama",
    generation: 3.2,
    paramsB: 3.2,
    quantization: "fp16",
    weightsMiB: 7_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: LLAMA_GATE_NOTE,
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    hfRepo: "meta-llama/Llama-3.3-70B-Instruct",
    family: "llama-3.3-70b",
    lineage: "llama",
    generation: 3.3,
    paramsB: 70.6,
    quantization: "fp16",
    weightsMiB: 140_000,
    sizeClass: "large",
    cpuFeasible: false,
    gated: true,
    notes: `${LLAMA_GATE_NOTE} Needs multi-GPU or 80GB+ class cards in fp16.`,
  },
  {
    id: "llama-4-scout-instruct",
    name: "Llama 4 Scout Instruct",
    hfRepo: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    family: "llama-4-scout",
    lineage: "llama",
    generation: 4,
    paramsB: 109,
    quantization: "fp16",
    weightsMiB: 207_000,
    sizeClass: "large",
    cpuFeasible: false,
    gated: true,
    notes: `${LLAMA4_GATE_NOTE} MoE 109B total / 17B active. Needs multi-GPU datacenter VRAM in fp16.`,
  },
  {
    id: "mistral-7b-instruct",
    name: "Mistral 7B Instruct v0.3",
    hfRepo: "mistralai/Mistral-7B-Instruct-v0.3",
    family: "mistral-7b",
    lineage: "mistral",
    generation: 0.3,
    paramsB: 7,
    quantization: "fp16",
    weightsMiB: 14_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: MISTRAL_GATE_NOTE,
  },
  {
    id: "mistral-7b-instruct-awq",
    name: "Mistral 7B Instruct AWQ",
    hfRepo: "TheBloke/Mistral-7B-Instruct-v0.2-AWQ",
    family: "mistral-7b",
    lineage: "mistral",
    generation: 0.3,
    paramsB: 7,
    quantization: "awq",
    weightsMiB: 4_500,
    sizeClass: "small",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    notes: AWQ_NOTE,
  },
  {
    id: "ministral-8b-instruct",
    name: "Ministral 8B Instruct",
    hfRepo: "mistralai/Ministral-8B-Instruct-2410",
    family: "ministral-8b",
    lineage: "mistral",
    generation: 2.4,
    paramsB: 8,
    quantization: "fp16",
    weightsMiB: 16_000,
    sizeClass: "small",
    cpuFeasible: false,
    gated: true,
    notes: MISTRAL_GATE_NOTE,
  },
  {
    id: "mistral-small-3.2-24b-instruct",
    name: "Mistral Small 3.2 24B Instruct",
    hfRepo: "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
    family: "mistral-small-3.2-24b",
    lineage: "mistral",
    generation: 3.2,
    paramsB: 24,
    quantization: "fp16",
    weightsMiB: 48_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    notes: "Ungated Apache-2.0. Text+image checkpoint; this app’s vLLM path is text chat. Typically needs two ~32 GiB GPUs or 80GB-class in fp16.",
  },
  {
    id: "qwen2.5-14b-instruct",
    name: "Qwen2.5 14B Instruct",
    hfRepo: "Qwen/Qwen2.5-14B-Instruct",
    family: "qwen2.5-14b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 14,
    quantization: "fp16",
    weightsMiB: 28_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen2.5-14b-instruct-awq",
    name: "Qwen2.5 14B Instruct AWQ",
    hfRepo: "Qwen/Qwen2.5-14B-Instruct-AWQ",
    family: "qwen2.5-14b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 14,
    quantization: "awq",
    weightsMiB: 9_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    notes: AWQ_NOTE,
  },
  {
    id: "qwen2.5-32b-instruct",
    name: "Qwen2.5 32B Instruct",
    hfRepo: "Qwen/Qwen2.5-32B-Instruct",
    family: "qwen2.5-32b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 32,
    quantization: "fp16",
    weightsMiB: 64_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
  },
  {
    id: "qwen2.5-32b-instruct-awq",
    name: "Qwen2.5 32B Instruct AWQ",
    hfRepo: "Qwen/Qwen2.5-32B-Instruct-AWQ",
    family: "qwen2.5-32b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 32,
    quantization: "awq",
    weightsMiB: 20_000,
    sizeClass: "medium",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    notes: AWQ_NOTE,
  },
  {
    id: "llama-3.1-70b-instruct",
    name: "Llama 3.1 70B Instruct",
    hfRepo: "meta-llama/Llama-3.1-70B-Instruct",
    family: "llama-3.1-70b",
    lineage: "llama",
    generation: 3.1,
    paramsB: 70,
    quantization: "fp16",
    weightsMiB: 140_000,
    sizeClass: "large",
    cpuFeasible: false,
    gated: true,
    notes: `${LLAMA_GATE_NOTE} Needs multi-GPU or 80GB+ class cards in fp16. Prefer the 4-bit variant.`,
  },
  {
    id: "llama-3.1-70b-instruct-awq",
    name: "Llama 3.1 70B Instruct AWQ",
    hfRepo: "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4",
    family: "llama-3.1-70b",
    lineage: "llama",
    generation: 3.1,
    paramsB: 70,
    quantization: "awq",
    weightsMiB: 40_000,
    sizeClass: "large",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    notes: `${LLAMA_AWQ_NOTE} Fits a single 48GB+ GPU with KV-cache headroom.`,
  },
  {
    id: "qwen2.5-72b-instruct-awq",
    name: "Qwen2.5 72B Instruct AWQ",
    hfRepo: "Qwen/Qwen2.5-72B-Instruct-AWQ",
    family: "qwen2.5-72b",
    lineage: "qwen",
    generation: 2.5,
    paramsB: 72,
    quantization: "awq",
    weightsMiB: 41_000,
    sizeClass: "large",
    cpuFeasible: false,
    gated: false,
    vllmQuantization: "awq",
    notes: "4-bit 72B-class; typically needs 48GB+ VRAM.",
  },
];

export function findCatalogModel(idOrRepo: string): CatalogModel | undefined {
  const needle = idOrRepo.trim();
  if (!needle) return undefined;
  return LOCAL_MODEL_CATALOG.find(
    (model) => model.id === needle || model.hfRepo === needle || model.hfRepo.toLowerCase() === needle.toLowerCase(),
  );
}

export function repoDirName(hfRepo: string): string {
  return hfRepo.replaceAll("/", "--");
}

/** Size class used to pick the newest Hub id when a lineage has several names. */
export function sizeSlot(paramsB: number): string {
  if (!Number.isFinite(paramsB) || paramsB < 1.2) return "tiny";
  if (paramsB < 2.8) return "2b";
  if (paramsB < 6) return "4b";
  if (paramsB < 13) return "12b";
  if (paramsB < 20) return "14b";
  if (paramsB < 40) return "32b";
  return "70b";
}

export function slotKey(model: Pick<CatalogModel, "lineage" | "paramsB">): string {
  return `${model.lineage}:${sizeSlot(model.paramsB)}`;
}

export function newestGenerationBySlot(catalog: readonly CatalogModel[]): Map<string, number> {
  const max = new Map<string, number>();
  for (const model of catalog) {
    const key = slotKey(model);
    const current = max.get(key) ?? Number.NEGATIVE_INFINITY;
    if (model.generation > current) max.set(key, model.generation);
  }
  return max;
}

export function isNewestHubId(
  model: CatalogModel,
  catalog: readonly CatalogModel[] = LOCAL_MODEL_CATALOG,
): boolean {
  const newest = newestGenerationBySlot(catalog).get(slotKey(model)) ?? model.generation;
  return model.generation >= newest;
}
